"""Stop condition for the demo loop: all of these must pass.

Run from this directory:   python -m unittest test_calc
The loop is DONE when this exits 0. Do not edit this file — fix calc.py.
"""
import unittest

from calc import add, is_even, factorial


class TestCalc(unittest.TestCase):
    def test_add(self):
        self.assertEqual(add(2, 3), 5)
        self.assertEqual(add(-1, 1), 0)
        self.assertEqual(add(0, 0), 0)

    def test_is_even(self):
        self.assertTrue(is_even(4))
        self.assertTrue(is_even(0))
        self.assertFalse(is_even(7))

    def test_factorial(self):
        self.assertEqual(factorial(0), 1)
        self.assertEqual(factorial(1), 1)
        self.assertEqual(factorial(5), 120)


if __name__ == "__main__":
    unittest.main()
